/********************************************************************
* tmp/modules/Pythia8Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/modules/Pythia8Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePythia8Dict();
extern void G__cpp_setup_inheritancePythia8Dict();
extern void G__cpp_setup_typetablePythia8Dict();
extern void G__cpp_setup_memvarPythia8Dict();
extern void G__cpp_setup_globalPythia8Dict();
extern void G__cpp_setup_memfuncPythia8Dict();
extern void G__cpp_setup_funcPythia8Dict();
extern void G__set_cpp_environmentPythia8Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Pythia8DictLN_TClass;
extern G__linked_taginfo G__Pythia8DictLN_TBuffer;
extern G__linked_taginfo G__Pythia8DictLN_TMemberInspector;
extern G__linked_taginfo G__Pythia8DictLN_TObject;
extern G__linked_taginfo G__Pythia8DictLN_TNamed;
extern G__linked_taginfo G__Pythia8DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Pythia8DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Pythia8DictLN_TObjArray;
extern G__linked_taginfo G__Pythia8DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Pythia8DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Pythia8DictLN_TIterator;
extern G__linked_taginfo G__Pythia8DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Pythia8DictLN_TTask;
extern G__linked_taginfo G__Pythia8DictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__Pythia8DictLN_ExRootTask;
extern G__linked_taginfo G__Pythia8DictLN_DelphesModule;
extern G__linked_taginfo G__Pythia8DictLN_Pythia8;
extern G__linked_taginfo G__Pythia8DictLN_Pythia8cLcLPythia;
extern G__linked_taginfo G__Pythia8DictLN_PileUpMergerPythia8;

/* STUB derived class for protected member access */
